#!/bin/sh
#
# Script to detect UNIX/Linux OS and varios aspects of the
# OS. Especially for Linux: distribution type and derivarite (such as
# CentOS/RHEL or Debian/Ubuntu)
#
# Author: Dmytro Kovalov, 2013, March 12-13
#
# Used these sources to start:
# http://www.novell.com/coolsolutions/feature/11251.html
# http://serverfault.com/questions/3331/how-do-i-find-out-what-version-of-linux-is-running
# http://www.unix.com/slackware/23652-determine-linux-version.html
#
# Script outputs results in the format that can either be parsed or
# directly eval'ed in Bourne shell:
#
# Example
# -----------
# sherlock
# OS=Linux
# MACH=x86_64
# KERNEL=2.6.32-5-amd64
# DISTRIBUTION=debian
# FAMILY=debian
# DERIVATIVE=Debian
# RELEASE=6.0.6
# CODENAME=squeeze
#
# CHANGES: Commented out echoes to minimize the output of this script. This is to achieve either a 
# Unix specific name (AIX,DARWIN) or a Linux distro name (debian,fedora) that can be piped into
# a variable for the ISO generation environment setup script.

PATH=/bin:/sbin:/usr/bin:/usr/sbin

####################################################################
# Functions
#

##
# Main function that call all others
#
detect_os () {

    OS=`uname -s`
#    MACH=`uname -m`

#    echo OS=$OS
#    echo MACH=$MACH

    if [ "${OS}" = "SunOS" ] ; then
#	    echo ARCH=`uname -p`	
#	    OSSTR="${OS} ${REV}(${ARCH} `uname -v`)"
#        echo FAMILY=solaris
         echo "${OS}"
    elif [ "${OS}" = "AIX" ] ; then
#	    echo OSSTR="${OS} `oslevel` (`oslevel -r`)"
#        echo FAMILY=aix
         echo "${OS}"
    elif [ "${OS}" = "Darwin" ] ; then
#        echo REV=`uname -r`
#        echo FAMILY=macosx
         echo "${OS}"
    elif [ "${OS}" = "Linux" ] ; then
# 	    echo KERNEL="`uname -r`"
        linux_distro
    fi
}




## ------------------------------------------------------------
# Redhat derivatives distros
#
redhat_derivative () {

    local FILE=/etc/redhat-release

    grep -i 'red.*hat.*enterprise.*linux' $FILE 2>&1 > /dev/null && { echo  "rhel"; return; }
    grep -i 'red.*hat.*linux' $FILE 2>&1 > /dev/null && { echo "rh"; return; }
    grep -i 'cern.*e.*linux' $FILE 2>&1 > /dev/null && { echo "cel"; return; }
    grep -i 'scientific linux cern' $FILE 2>&1 > /dev/null && { echo "slc"; return; }
    grep -i 'centos' $FILE 2>&1 > /dev/null && { echo "centos"; return; }
    grep -i 'fedora' $FILE 2>&1 > /dev/null && { echo "fedora"; return; }
    echo DERIVATIVE=unknown
}


#redhat_release () {
#    echo RELEASE=`tr -d 'a-zA-Z [](){}' < /etc/redhat-release`
#}

## ------------------------------------------------------------
# Debian derivatives
#
debian_derivative () {
    if which lsb_release 2>&1 > /dev/null ; then
        echo `lsb_release --id --short 2> /dev/null`
#        echo RELEASE=`lsb_release --release --short 2> /dev/null`
#        echo CODENAME=`lsb_release --codename --short 2> /dev/null`
        return
    else
        echo DERIVATIVE=unknown
        echo RELEASE=`cat /etc/debian_version`
        echo CODENAME=unknown
        return
    fi
}

##
#
#
linux_distro () {

	if [ -f /etc/redhat-release ] ; then
#		echo DISTRIBUTION=redhat
#        echo FAMILY=rh
        redhat_derivative
#        redhat_release
    elif [ -s /etc/slackware-version ]; then
        echo "slackware"
#	elif [ -f /etc/SUSE-release ] ; then
        # TODO - not tested
        echo "suse"
# 		echo PSUEDONAME=`cat /etc/SUSE-release | tr "\n" ' '| sed s/VERSION.*//`
# 		echo REV=`cat /etc/SUSE-release | tr "\n" ' ' | sed s/.*=\ //`
#        echo VERSION=`cat /etc/SuSE-release | grep 'VERSION' | sed  -e 's#[^0-9]##g'`
	elif [ -f /etc/mandrake-release ] ; then
        # TODO - not tested
        echo "mandrake"
# 		echo PSUEDONAME=`cat /etc/mandrake-release | sed s/.*\(// | sed s/\)//`
# 		echo REV=`cat /etc/mandrake-release | sed s/.*release\ // | sed s/\ .*//`
#        echo FAMILY=rh
	elif [ -f /etc/debian_version ] ; then
#        echo DISTRIBUTION=debian
#        echo FAMILY=debian
        debian_derivative
    elif [ -f /etc/UnitedLinux-release ]; then
        echo "united"
#        echo VERSION=`cat /etc/UnitedLinux-release`
    elif [ -r /etc/init.d/functions.sh ]; then
        # TODO - not tested 
        source /etc/init.d/functions.sh
        [ zz`type -t ebegin 2>/dev/null` == "zzfunction" ] && echo "gentoo"
    elif [ -f /etc/arch-release ] ; then
    	echo "arch"
	fi
}

# --------------------------------------------------------------------------------
# Do it!
#
detect_os


