name: Main
on:
  workflow_dispatch:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build dappnode ISO
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: create iso
        run: |
          docker-compose build
          docker-compose up
      - name: verify image
        run: |
          ls -lrt images/DappNode-ubuntu-*
