name: Pre-release

on:
  push:
    branches:
      - "v*.*.*"

jobs:
  release:
    name: create pre release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Build
        run: |
          docker-compose build
          docker-compose up
      - name: Check iso
        run: |
          ls -lrt images/DAppNode-debian-bullseye-amd64.iso
      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.base_ref == 'refs/heads/master'
        with:
          tag_name: ${BRANCH_NAME}
          prerelease: true
          files: |
            ./images/DAppNode-debian-bullseye-amd64.iso
            ./scripts/dappnode_install.sh
            ./scripts/dappnode_install_pre.sh
            ./scripts/dappnode_uninstall.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
