name: Pre-release

on:
  push:
    branches:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  pre-release:
    name: create pre release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: get latest tag release
        id: latest_release
        uses: oprypin/find-latest-tag@v1
        with:
          repository: dappnode/DNP_CORE
          releases-only: true
      - name: remove v from version
        id: remove_v
        run: |
          version=$(echo ${{ steps.latest_release.outputs.tag }} | cut -c2-)
          echo "::set-output name=version::$version"
      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.remove_v.outputs.version }}
          version-fragment: "bug"
      - name: add v to version
        id: add_v
        run: |
          version_final="v${{ steps.bump_version.outputs.next-version }}"
          echo "::set-output name=version_final::$version_final"
      - name: Build
        run: |
          docker-compose build
          docker-compose up
      - name: Check iso
        run: |
          ls -lrt images/DAppNode-debian-bullseye-amd64.iso
      - name: Create dappnode_profile.sh
        run: |
          cp .dappnode_profile dappnode_profile.sh
      - name: Pre release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.add_v.outputs.version_final }}
          prerelease: true
          files: |
            ./images/DAppNode-debian-bullseye-amd64.iso
            ./scripts/dappnode_install.sh
            ./scripts/dappnode_install_pre.sh
            ./scripts/dappnode_uninstall.sh
            ./scripts/dappnode_access_credentials.sh
            .dappnode_profile.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
